### ISSUE TITLE
No way to select video file in Samsung One UI 3.1.

### ISSUE THREAD

**Issue by sxryr** [chromaticnoob/syncplay-android#1]
Absence of File Browser in one UI 3.1 from selection sheet after taping add video icon in player.
![image](https://user-images.githubusercontent.com/24762595/166100716-c309e650-582a-4e13-82f6-6d5ed6aa8877.png)

**Comment by chromaticnoob** [comment]
That is weird indeed, I appreciate the report. Everything seems to be working fine on MIUI OS and OxygenOS systems as well as older Samsung One UI systems. However, I believe I already know what's causing the issue and I will be fixing it very soon.

Meanwhile, you could try downloading a "custom file manager" from Google Play Store. It **may or may not appear** among the options upon clicking the choose-vid button.

**Comment by chromaticnoob** [comment]
Fixed in version 0.4.0j.
