### ISSUE TITLE
.mkv file with DCA audio does not have sound when played in syncplay-android

### ISSUE THREAD

**Issue by soredake** [chromaticnoob/syncplay-android#2]
Title.

**Comment by soredake** [comment]
Test files can be found here https://thedigitaltheater.com/dts-trailers/
I've tested "Animated Logo"

**Comment by soredake** [comment]
@chromaticnoob it's okay, and thanks for syncplay for android!

**Comment by chromaticnoob** [comment]
Fixed in version [0.6.3j](https://github.com/chromaticnoob/syncplay-android/releases/tag/0.6.3j). Enabled FFmpegAudioRenderer which now supports a variety of formats as stated here [ExoPlayer:FFmpeg's Supported Audio Formats](https://exoplayer.dev/supported-formats.html#ffmpeg-extension)
