### ISSUE TITLE
cannot load .srt subtitles file

### ISSUE THREAD

**Issue by sxryr** [chromaticnoob/syncplay-android#4]
![Screenshot_2022-06-03-23-04-55-800_com gintoki syncplay](https://user-images.githubusercontent.com/24762595/171921287-306aadd8-c1e7-4cb2-9d75-7664ff30629b.jpg)
[sonic-the-hedgehog_HI_english-2652672.zip](https://github.com/chromaticnoob/syncplay-android/files/8835101/sonic-the-hedgehog_HI_english-2652672.zip)

attached subtitles file, using v0.5.1a on Android 12 (miui 13), mi 11 lite 5g ne

**Comment by chromaticnoob** [comment]
Please provide the following information : 
- The subtitle file being used (A download link would be appreciated, or just attach it to your reply)
- Syncplay version in use (Using 0.5.1-BETA is recommended)
- Device being used as well as the Android version.

**Comment by sxryr** [comment]
updated issue, please check

**Comment by chromaticnoob** [comment]
Thanks for the feedback @sxryr. There seems to be a small issue concerning the lines of code responsible for importing subtitles. Will fix it as soon as possible some time today or tomorrow.

**Comment by chromaticnoob** [comment]
Fixed in version [0.5.2a](https://github.com/chromaticnoob/syncplay-android/releases/tag/0.5.2a)
